### ISSUE TITLE
不懂“没有用第三方那个库来分拆”是什么意思

### ISSUE THREAD

**Issue by ruanhuhu** [easychen/openai-gpt-dev-notes-for-cn-developer#2]
Token计算和限制问题：如果使用者用自己的Key，为了提升体验，我们可以提供一个Token计算，让用户知道自己的会花多少钱。另外如果你没有用第三方那个库来分拆，那么一次请求的内容不要超过 max_tokens 的限制。这个值一般是 4096。

——
意思是chatgpt-api这个库可以把很长的内容拆分很多个请求？然后再组装回复的数据返回吗？

**Comment by easychen** [comment]
如果指定parent id ，它会帮你处理聊天历史记录的问题（连续对话）。但不会直接拆内容。
