### ISSUE TITLE
第三方接口是否足够稳定可靠，可否供企业使用

### ISSUE THREAD

**Issue by montaro2017** [easychen/openai-gpt-dev-notes-for-cn-developer#4]
或者有无稳定可靠的第三方接口

**Comment by easychen** [comment]
先把问题分成两个吧，一个是 稳定、一个是频次上是否可供企业使用。

首先要具体化「可供企业使用」这个词，比如具体到每分钟多少个并发连接。据我所知，api2d 的个人版（默认就是）每账户每分钟限制为60次请求；而企业版可以单独为你部署服务器、使用单独域名、启动独立的openai账号，具体价格和你的要求相关，可以加他们微信群的群主聊细节。

处理好了并发，其他的稳定性就没太多问题，毕竟就是很薄一层代理，但目前所有第三方接口都不够稳定。因为OpenAI自己经常宕机，第三方也只能挂 …

**Comment by montaro2017** [comment]
> 先把问题分成两个吧，一个是 稳定、一个是频次上是否可供企业使用。
> 
> 首先要具体化「可供企业使用」这个词，比如具体到每分钟多少个并发连接。据我所知，api2d 的个人版（默认就是）每账户每分钟限制为60次请求；而企业版可以单独为你部署服务器、使用单独域名、启动独立的openai账号，具体价格和你的要求相关，可以加他们微信群的群主聊细节。
> 
> 处理好了并发，其他的稳定性就没太多问题，毕竟就是很薄一层代理，但目前所有第三方接口都不够稳定。因为OpenAI自己经常宕机，第三方也只能挂 …

好的，感谢
