### ISSUE TITLE
不能访问api

### ISSUE THREAD

**Issue by alon-qianyue** [easychen/openai-gpt-dev-notes-for-cn-developer#7]
腾讯函数 硅谷和新加坡都试了，还是Your access was terminated due to violation of our policies，是不是不止封ip，还会关联user

**Comment by easychen** [comment]
看这个提示，好像是账号本身就被禁用了。

**Comment by alon-qianyue** [comment]
> 看这个提示，好像是账号本身就被禁用了。

但是我gpt可以用，🤣

**Comment by easychen** [comment]
> > 看这个提示，好像是账号本身就被禁用了。
> 
> 但是我gpt可以用，🤣

网页版和api是两个产品。
